production:
  clients:
    default:
      uri: mongodb+srv://sustare_atlas_user:<%="#{ENV['MONGO_PASS']}"%>@sandbox.z93w8.mongodb.net/dinner?retryWrites=true&w=majority
      options:
        read:
          mode: :secondary_preferred
          tag_sets:
            - use: web
        server_selection_timeout: 7

development:
  clients:
    default:
      database: dinner_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

test:
  clients:
    default:
      database: dinner_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
        user: 'root'
        password: 'rootpassword'
        auth_source: admin

